import { Download, Info, Settings2, TrendingUp } from "lucide-react";

import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const students = [
  { name: "Nadia Putri", assignment: 88, quiz: 92, final: 89.6 },
  { name: "Rafi Nugraha", assignment: 76, quiz: 81, final: 78 },
  { name: "Farhan Akbar", assignment: 94, quiz: 90, final: 92.4 },
  { name: "Siti Maharani", assignment: 82, quiz: 86, final: 83.6 },
];

export function Gradebook() {
  return <div className="space-y-6"><PageHeader eyebrow="Mathematics · Grade 10A" title="Gradebook" description="Review backend-calculated assignment and quiz contributions for the active term." actions={<><Button variant="outline"><Settings2 className="h-4 w-4" />Weights</Button><Button><Download className="h-4 w-4" />Export CSV</Button></>} /><section className="grid gap-4 sm:grid-cols-3">{[{ label: "Class average", value: "84.8%" }, { label: "Assignment weight", value: "60%" }, { label: "Quiz weight", value: "40%" }].map((item) => <Card key={item.label}><CardContent className="p-5"><p className="text-3xl font-bold">{item.value}</p><p className="mt-1 text-sm text-muted-foreground">{item.label}</p></CardContent></Card>)}</section><Card><CardHeader><CardTitle>Student results</CardTitle><CardDescription>Ungraded and exempt assessments are excluded from the applicable category total.</CardDescription></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[700px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Assignments</th><th className="px-5 py-3">Quizzes</th><th className="px-5 py-3">Final grade</th><th className="px-5 py-3">Trend</th></tr></thead><tbody>{students.map((student) => <tr key={student.name} className="border-t"><td className="px-5 py-4 font-semibold">{student.name}</td><td className="px-5 py-4">{student.assignment}%</td><td className="px-5 py-4">{student.quiz}%</td><td className="px-5 py-4"><Badge variant="success">{student.final}%</Badge></td><td className="px-5 py-4"><span className="inline-flex items-center gap-1 text-emerald-700"><TrendingUp className="h-4 w-4" />Improving</span></td></tr>)}</tbody></table></CardContent></Card><Card className="bg-blue-50"><CardContent className="flex gap-3 p-5 text-blue-950"><Info className="mt-0.5 h-5 w-5 shrink-0 text-blue-700" /><div><p className="font-semibold">Calculation policy</p><p className="mt-1 text-sm leading-6 text-blue-800">Missing work counts as zero only after it is explicitly marked missing. Exempt work is excluded, and ungraded work does not affect the current grade.</p></div></CardContent></Card></div>;
}

export function ReportsWorkspace() {
  return <div className="space-y-6"><PageHeader eyebrow="Analytics" title="Reports" description="Move from individual learning outcomes to course and school-wide trends." actions={<Button><Download className="h-4 w-4" />Export current view</Button>} /><section className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[{ label: "Overall grade", value: "84.8%" }, { label: "Attendance", value: "94.6%" }, { label: "Course progress", value: "78%" }, { label: "On-time submissions", value: "91%" }].map((item) => <Card key={item.label}><CardContent className="p-5"><p className="text-3xl font-bold">{item.value}</p><p className="mt-1 text-sm text-muted-foreground">{item.label}</p></CardContent></Card>)}</section><section className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Performance by course</CardTitle><CardDescription>Average grade and learning progress.</CardDescription></CardHeader><CardContent className="space-y-5">{[{ name: "Mathematics", grade: 85, progress: 78 }, { name: "Biology", grade: 81, progress: 64 }, { name: "Indonesian Literature", grade: 88, progress: 83 }].map((item) => <div key={item.name}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{item.name}</span><span>{item.grade}% average</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${item.progress}%` }} /></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Attendance distribution</CardTitle><CardDescription>Active academic year across all recorded sessions.</CardDescription></CardHeader><CardContent className="space-y-3">{[{ label: "Present", value: 94.6, color: "bg-emerald-500" }, { label: "Late", value: 2.1, color: "bg-amber-500" }, { label: "Excused or sick", value: 2.4, color: "bg-blue-500" }, { label: "Absent", value: 0.9, color: "bg-red-500" }].map((item) => <div key={item.label} className="flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${item.color}`} /><span className="flex-1 text-sm">{item.label}</span><span className="font-semibold">{item.value}%</span></div>)}</CardContent></Card></section></div>;
}
